name: mybook
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/book_cover.jpeg
    - assets/author_image.jpeg
    - assets/chapter1.json
    - assets/chapter2.json
    - assets/chapter3.json
    - assets/chapter4.json
    - assets/chapter5.json
    - assets/chapter6.json
    - assets/chapter7.json
    - assets/chapter8.json
    - assets/chapter9.json
    - assets/chapter10.json
    - assets/chapter11.json
    - assets/chapter12.json

  # example:
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
