name: lavij
description: "A Kurdisk book app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_staggered_grid_view: ^0.7.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: AliKAlwand
      fonts:
        - asset: assets/fonts/Ali-K-Alwand.ttf

    - family: FindiKIsam
      fonts:
        - asset: assets/fonts/FINDI_K_ISAM.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/12_1/
    - assets/images/12_2/1/
    - assets/images/12_2/2/
    - assets/images/12_2/3/
    - assets/images/12_2/4/
    - assets/images/12_2/5/
    - assets/images/12_2/6/
    - assets/images/12_2/7/
    - assets/images/12_2/8/
    - assets/images/12_2/10/
    - assets/images/12_2/11/
    - assets/images/12_2/12/
    - assets/images/12_2/13/
    - assets/images/12_2/16/
    - assets/images/12_3/1/
    - assets/images/12_3/2/
    - assets/images/12_3/3/
    - assets/images/12_3/4/
    - assets/images/12_4/1/
    - assets/images/12_4/2/
    - assets/images/12_4/3/
    - assets/images/12_4/4/
    - assets/images/12_4/5/
    - assets/images/12_4/6/
    - assets/images/12_4/7/
    - assets/images/12_4/8/
    - assets/images/12_4/9/
    - assets/images/12_4/10/
    - assets/images/12_5/1/
    - assets/images/12_5/2/
    - assets/images/12_5/3/
    - assets/images/12_5/4/
    - assets/images/12_5/5/
    - assets/images/12_6/1/
    - assets/images/12_6/2/
    - assets/images/12_6/3/
    - assets/images/12_7/1/
    - assets/images/12_7/2/
    - assets/images/12_8/1/
    - assets/images/12_8/2/
    - assets/images/12_8/3/
    - assets/images/12_8/4/
    - assets/images/12_8/5/
    - assets/images/12_8/6/
    - assets/images/12_8/7/
    - assets/images/12_8/8/
    - assets/images/12_8/10/
    - assets/images/12_8/11/
    - assets/images/12_9/1/
    - assets/images/12_9/2/
    - assets/images/12_10/1/
    - assets/images/12_11/1/
    - assets/images/12_11/2/
    - assets/images/12_12/1/
    - assets/book_cover.jpeg
    - assets/author_image.jpeg
    - assets/chapter1.json
    - assets/chapter2.json
    - assets/chapter3.json
    - assets/chapter4.json
    - assets/chapter5.json
    - assets/chapter6.json
    - assets/chapter7.json
    - assets/chapter8.json
    - assets/chapter9.json
    - assets/chapter10.json
    - assets/chapter11.json
    - assets/table_of_content.json
    - assets/pics.json

  # example:
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
